### ISSUE TITLE
Getting compiler error

### ISSUE THREAD

**Issue by bvssvni** [autumnai/leaf-examples#1]
```
 expected `collections::vec::Vec<usize>`,
    found `collections::vec::Vec<isize>`
(expected usize,
    found isize) [E0308]
/Users/sven/.cargo/registry/src/github.com-0a35038f75765ae4/cuticula-0.1.2/src/transformer.rs:15         let mut blob = Box::new(Blob::of_shape(shape));
                                                                                                                                                ^~~~~
/Users/sven/.cargo/registry/src/github.com-0a35038f75765ae4/cuticula-0.1.2/src/transformer.rs:15:48: 15:53 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `cuticula`.
```

**Comment by hobofan** [comment]
Can confirm the error.

In an older version of phloem the shape was of type `Vec<isize>`. From a quick glance the crate version seems to be locked correctly to 0.2.1 but it still pulls 0.2.4.

We also should consider to commit the `Cargo.lock` to the repo.

**Comment by hobofan** [comment]
@MichaelHirn can you take a look?

**Comment by MichaelHirn** [comment]
Totally and thanks @bvssvni :+1: 

Locked the version on cuticula; updated it to 0.1.4 and then used this version here in the examples. I also shiped the Cargo.lock to avoid some fancy verion pulls.
